### ISSUE TITLE
Assets fail to load after game patch 1.1.6f, and on mod version 1.4.0 and 1.3.0

### ISSUE THREAD

**Issue by Ezilii** [CitiesSkylinesModding/CS2-AssetPacksManager#7]
## What is the issue
Assets fail to load after game patch 1.1.6f, and on mod version 1.4.0 and 1.3.0

## When does the issue appear?
It is only notable in city game. The game appears to load this mod and assets in the notifications list, however installed assets result in boxes and missing UI tabs, example More Parking's tab in the Roads Tools is missing.

## Have you used the `Delete Mods Cache`-Option in Asset Packs Manager? If not, why not?
Yes, it was my first step going into the patch.

## Have you deleted the `C:/Users/%username%/AppData/LocalLow/Colossal Order/Cities Skylines II/Mods` folder? If not, why not?
No

## Have you deleted the `C:/Users/%username%/AppData/LocalLow/Colossal Order/Cities Skylines II/CustomAssets` folder? If not, why not?
This folder doesn't exist but `StreamingData~ does, which has my local assets in it. My local assets load just fine, but subscribed assets do not.

## Attached Logs from `C:/Users/%username%/AppData/LocalLow/Colossal Order/Cities Skylines II/Logs`
[LogReport_24-07-03_10-07.zip](https://github.com/user-attachments/files/16086946/LogReport_24-07-03_10-07.zip)

**Comment by maximeg** [comment]
Hello, same here.

I have only 3 mods with assets, none of them appear in the game.

Log: [AssetPacksManager.Mod](https://github.com/user-attachments/files/16096333/AssetPacksManager.Mod.txt)

I'm not sure this works: https://github.com/kosch104/CS2-AssetPacksManager/commit/ef3cde478ea6876ba5dacd2a3c9f7159aafd7324#diff-10dae8f85a591c3e35b0faf632ae9356af84e81e945d225c6cf0a00db50d6fdeR376-R385

**Comment by CodingMoeButa** [comment]
I have the same problem.

**Comment by Mimonsi** [comment]
This should have been fixed with latest version, can you please confirm?

**Comment by jynxy** [comment]
@kosch104  still does not work.

[object Object]
NullReferenceException: Object reference not set to an instance of an object
  at Colossal.IO.AssetDatabase.PrefabAsset+PrefabReferenceResolver.TryResolveReference (System.String id, System.Object& value) [0x00052] in <57b5f3e4302043fda596a7ba689e15a7>:0 
  at Colossal.OdinSerializer.DeserializationContext.GetExternalObject (System.String id) [0x00033] in <5fbd906329d843a4a9e7066a41ace735>:0 
  at Colossal.OdinSerializer.AnySerializer.ReadValueWeak (Colossal.OdinSerializer.IDataReader reader) [0x006df] in <5fbd906329d843a4a9e7066a41ace735>:0 
  at Colossal.OdinSerializer.ReflectionFormatter`1[T].DeserializeImplementation (T& value, Colossal.OdinSerializer.IDataReader reader) [0x0013d] in <5fbd906329d843a4a9e7066a41ace735>:0 
Colossal.Logging.CustomLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
Colossal.OdinSerializer.CustomLogger:LogException(Exception)
Colossal.OdinSerializer.DebugContext:LogException(Exception)
Colossal.OdinSerializer.ReflectionFormatter`1:DeserializeImplementation(SpawnableBuilding&, IDataReader)
Colossal.OdinSerializer.BaseFormatter`1:Deserialize(IDataReader)
Colossal.OdinSerializer.BaseFormatter`1:Colossal.OdinSerializer.IFormatter.Deserialize(IDataReader)
Colossal.OdinSerializer.ComplexTypeSerializer`1:ReadValue(IDataReader)
Colossal.OdinSerializer.ListFormatter`1:DeserializeImplementation(List`1&, IDataReader)
Colossal.OdinSerializer.BaseFormatter`1:Deserialize(IDataReader)
Colossal.OdinSerializer.BaseFormatter`1:Colossal.OdinSerializer.IFormatter.Deserialize(IDataReader)
Colossal.OdinSerializer.AnySerializer:ReadValueWeak(IDataReader)
Colossal.OdinSerializer.ReflectionFormatter`1:DeserializeImplementation(BuildingPrefab&, IDataReader)
Colossal.OdinSerializer.BaseFormatter`1:Deserialize(IDataReader)
Colossal.OdinSerializer.BaseFormatter`1:Colossal.OdinSerializer.IFormatter.Deserialize(IDataReader)
Colossal.OdinSerializer.AnySerializer:ReadValueWeak(IDataReader)
Colossal.OdinSerializer.SerializationUtility:DeserializeValueWeak(IDataReader)
Colossal.OdinSerializer.SerializationUtility:DeserializeValueWeak(Stream, DataFormat, DeserializationContext)
Colossal.IO.AssetDatabase.PrefabAsset:Load()
AssetPacksManager.<LoadAssets>d__30:MoveNext() (at C:\Users\Konsi\Documents\CS2-Modding\CS2-AssetPacksManager\AssetPackLoaderSystem.cs:462)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
UnityEngine.MonoBehaviour:StartCoroutineManaged2(MonoBehaviour, IEnumerator)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
AssetPacksManager.<PrepareAssets>d__29:MoveNext() (at C:\Users\Konsi\Documents\CS2-Modding\CS2-AssetPacksManager\AssetPackLoaderSystem.cs:428)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

**Comment by Mimonsi** [comment]
You also tried enabling adaptive asset loading in the settings?

**Comment by jynxy** [comment]
[object Object]
NullReferenceException: Object reference not set to an instance of an object
  at Colossal.IO.AssetDatabase.PrefabAsset+PrefabReferenceResolver.TryResolveReference (System.String id, System.Object& value) [0x00052] in <57b5f3e4302043fda596a7ba689e15a7>:0 
  at Colossal.OdinSerializer.DeserializationContext.GetExternalObject (System.String id) [0x00033] in <5fbd906329d843a4a9e7066a41ace735>:0 
  at Colossal.OdinSerializer.AnySerializer.ReadValueWeak (Colossal.OdinSerializer.IDataReader reader) [0x006df] in <5fbd906329d843a4a9e7066a41ace735>:0 
  at Colossal.OdinSerializer.ReflectionFormatter`1[T].DeserializeImplementation (T& value, Colossal.OdinSerializer.IDataReader reader) [0x0013d] in <5fbd906329d843a4a9e7066a41ace735>:0 
Colossal.Logging.CustomLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
Colossal.OdinSerializer.CustomLogger:LogException(Exception)
Colossal.OdinSerializer.DebugContext:LogException(Exception)
Colossal.OdinSerializer.ReflectionFormatter`1:DeserializeImplementation(SpawnableBuilding&, IDataReader)
Colossal.OdinSerializer.BaseFormatter`1:Deserialize(IDataReader)
Colossal.OdinSerializer.BaseFormatter`1:Colossal.OdinSerializer.IFormatter.Deserialize(IDataReader)
Colossal.OdinSerializer.ComplexTypeSerializer`1:ReadValue(IDataReader)
Colossal.OdinSerializer.ListFormatter`1:DeserializeImplementation(List`1&, IDataReader)
Colossal.OdinSerializer.BaseFormatter`1:Deserialize(IDataReader)
Colossal.OdinSerializer.BaseFormatter`1:Colossal.OdinSerializer.IFormatter.Deserialize(IDataReader)
Colossal.OdinSerializer.AnySerializer:ReadValueWeak(IDataReader)
Colossal.OdinSerializer.ReflectionFormatter`1:DeserializeImplementation(BuildingPrefab&, IDataReader)
Colossal.OdinSerializer.BaseFormatter`1:Deserialize(IDataReader)
Colossal.OdinSerializer.BaseFormatter`1:Colossal.OdinSerializer.IFormatter.Deserialize(IDataReader)
Colossal.OdinSerializer.AnySerializer:ReadValueWeak(IDataReader)
Colossal.OdinSerializer.SerializationUtility:DeserializeValueWeak(IDataReader)
Colossal.OdinSerializer.SerializationUtility:DeserializeValueWeak(Stream, DataFormat, DeserializationContext)
Colossal.IO.AssetDatabase.PrefabAsset:Load()
AssetPacksManager.<LoadAssets>d__30:MoveNext() (at C:\Users\Konsi\Documents\CS2-Modding\CS2-AssetPacksManager\AssetPackLoaderSystem.cs:462)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

**Comment by jynxy** [comment]
cant get to settings.

**Comment by jynxy** [comment]
@kosch104 you online now ?

**Comment by Mimonsi** [comment]
On mobile yes

**Comment by jynxy** [comment]
ok, was going to diagnose with you online.

**Comment by Mimonsi** [comment]
Please delete this folder:
`C:\Users\%username%\AppData\LocalLow\Colossal Order\Cities Skylines II\.cache\Mods\mods_subscribed`
and then try again. All your mods will automatically be re-downloaded.
